amu_siamu_maintenance:
  url: https://siamu.univ-amu.fr/ws/
  urlApp: ws_appli
  urlAppSource: ws_appli_source
  idApp: 164 # Récuperez l'id de votre application DANS SIAMU (https://siamu.univ-amu.fr/application/)
  current: false

when@dev:
  amu_siamu_maintenance:
    url: https://siamu.dev.univ-amu.fr/ws/