twig:
  default_path: '%kernel.project_dir%/templates'
  globals:
    app_title: 'Nom Application'
    app_footer: 'DirNum - Pôle Développement - Aix-Marseille Université'
    siamu_ws: '@App\Service\Siamu'

when@test:
  twig:
    strict_variables: true
