twig:
  default_path: '%kernel.project_dir%/templates'
  globals:
    app_title: 'Nom Application'
    siamu_ws: '@Amu\SiamuMaintenanceBundle\Service\SiamuService'

when@test:
  twig:
    strict_variables: true
